language: rust

install:
    - sudo apt-get install libXxf86vm-dev libosmesa6-dev

after_success:
    - |
        [ $TRAVIS_BRANCH = master ] &&
        [ $TRAVIS_PULL_REQUEST = false ] &&
        cargo publish --token ${CRATESIO_TOKEN}
