[package]
name = "glium_text"
version = "0.7.0"
authors = ["Pierre Krieger <pierre.krieger1708@gmail.com>"]
description = "Text drawing with glium and freetype"
keywords = ["text", "opengl"]
license = "MIT"

[dependencies]
freetype-sys = "0.2"
libc = "0.2"

[dependencies.glium]
version = "0.13"
default-features = false

[dev-dependencies]
cgmath = "0.7"

[dev-dependencies.glium]
version = "0.13"
features = ["glutin"]
