[package]
name = "glium_text"
version = "0.0.1"
authors = ["Pierre Krieger <pierre.krieger1708@gmail.com>"]
description = "Text drawing with glium and freetype"
keywords = ["text", "opengl"]

[dependencies.glium]
git = "https://github.com/tomaka/glium"
default-features = false
features = ["nalgebra"]

[dependencies.glium_macros]
git = "https://github.com/tomaka/glium"

[dependencies.freetype-sys]
git = "https://github.com/PistonDevelopers/freetype-sys"

[dependencies.nalgebra]
git = "https://github.com/sebcrozet/nalgebra"
