[package]
name = "glium_text"
version = "0.1.1"
authors = ["Pierre Krieger <pierre.krieger1708@gmail.com>"]
description = "Text drawing with glium and freetype"
keywords = ["text", "opengl"]
license = "MIT"

[dependencies]
freetype-sys = "*"
libc = "0.1"

[dependencies.glium]
version = "0.3"
default-features = false
features = ["cgmath"]

[dev-dependencies]
glutin = "0.1"
cgmath = "0.1"
