[package]
name = "glium_text"
version = "0.0.4"
authors = ["Pierre Krieger <pierre.krieger1708@gmail.com>"]
description = "Text drawing with glium and freetype"
keywords = ["text", "opengl"]
license = "MIT"

[dependencies]
freetype-sys = "*"
libc = "0.1"
nalgebra = "*"

[dependencies.glium]
version = "0.3"
default-features = false
features = ["nalgebra"]

[dev-dependencies]
glutin = "*"
